title: Savko Plastics Manufacturing
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
collections:
    products:
      output: true
      permalink: /products/:name
defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
